[simulation.ui]
title = 'Emotional Agents'
description = 'Simulation designed to explore creating agents as a hierarchy of internal systems.'
instructions = 'Click the start button to begin the simulation.'

# Declaring the tasks (i.e. coroutines) used by the scene is optional, but helps
# with keeping straight what functions you've already declared.
tasks = [
  'agents_spinning'
]

[scene]
cell_size = [20, 20] # In pixels.
height = 1300        # In pixels.
layers = [ # The layers that you want to show up on the layer menu.
  { label = 'Grid',             renderer = 'render_grid_layer',         show = false},
  { label = 'Entities',         renderer = 'render_entities_layer',     show = true},
  { label = 'Navigation Mesh',  renderer = 'render_nav_mesh_layer',     show = false},
  { label = 'Agents',           renderer = 'render_agents_layer',       show = true},
  { label = "Agent's AABB",     renderer = 'render_agents_aabb_layer',  show = false},
]

agents = [
  { id = 1, crest='green', location=[10,10]}
]

# Schedule the tasks you want to run.
# Add a task for cluster of agents that are rotating.
[[scene.schedule]]
coroutine = 'agents_spinning'
agent_ids = [1]
speeds = [0.01]
run_per_frame = 1